###################### Logz.io Winlogbeat Configuration Example ########################

winlogbeat.event_logs:
  - name: Application
  - name: Security
  - name: System

#==================== Logz.io =========================

fields:
  logzio_codec: json
  token: <<SHIPPING_TOKEN>>
  type: wineventlog
fields_under_root: true

#==================== Output ==========================

output.logstash:
  hosts: ["<<LISTENER_URL>>:5015"]
  ssl:
    certificate_authorities: ['C:\ProgramData\Filebeat\COMODORSADomainValidationSecureServerCA.crt']

#The following processors are to ensure compatibility with version 7
processors:
- rename:
    fields:
     - from: "agent"
       to: "beat_agent"
    ignore_missing: true
- rename:
    fields:
     - from: "log.file.path"
       to: "source"
    ignore_missing: true